### ISSUE TITLE
Uploading photos by exif ony works with full path

### ISSUE THREAD

**Issue by hbogner** [openstreetview/uploader#11]
When trying to upload photos with upload_photos_by_exif.py and entering relative path i get this error:

```
:~/git/uploader/upload_photos_by_exif$ python3 upload_photos_by_exif.py -p 2016_08_01_sg2_1/
Traceback (most recent call last):
  File "upload_photos_by_exif.py", line 411, in <module>
    main(sys.argv[1:])
  File "upload_photos_by_exif.py", line 297, in main
    photos_path = sorted(os.listdir(path), key=os.path.getmtime)
FileNotFoundError: [Errno 2] No such file or directory: '2016_08_01_sg2_1/'
```
I can only proceed if i enter full path:
`:~/git/uploader/upload_photos_by_exif$ python3 upload_photos_by_exif.py -p /home/hbogner/git/uploader/upload_photos_by_exif/2016_08_01_sg2_1/`

Should I be able to set relative and not absolute path?

**Comment by bogdan-telenav** [comment]
@hbogner I will investigate and fix this.
Thanks for helping 👍

**Comment by hbogner** [comment]
Photos folder is in the same folder where the script is.
Inside uploader/upload_photos_by_exif/

**Comment by bogdan-telenav** [comment]
We fixed this issue but we investigate more the other you post @hbogner Thanks for helping
