### ISSUE TITLE
Fix upload_photos_by_exif.py to work with Mapillary EXIF

### ISSUE THREAD

**Issue by hbogner** [openstreetview/uploader#12]
I have a lot of photos taken with Mapillary app and would like to upload them to OSV too.

When I start upload_photos_by_exif.py with full path i get this error:

```
:~/git/uploader/upload_photos_by_exif$ python3 upload_photos_by_exif.py -p /home/hbogner/git/uploader/upload_photos_by_exif/2016_08_01_sg2_1/
/home/hbogner/git/uploader/upload_photos_by_exif/osv/local/lib/python3.5/site-packages/PIL/TiffImagePlugin.py:680: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3806836976 bytes but only got 0. Skipping tag 14286
  "Skipping tag %s" % (size, len(data), tag))
/home/hbogner/git/uploader/upload_photos_by_exif/osv/local/lib/python3.5/site-packages/PIL/TiffImagePlugin.py:680: UserWarning: Possibly corrupt EXIF data.  Expecting to read 24032256 bytes but only got 0. Skipping tag 4352
  "Skipping tag %s" % (size, len(data), tag))
/home/hbogner/git/uploader/upload_photos_by_exif/osv/local/lib/python3.5/site-packages/PIL/TiffImagePlugin.py:694: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 3.
  warnings.warn(str(msg))
Traceback (most recent call last):
  File "upload_photos_by_exif.py", line 411, in <module>
    main(sys.argv[1:])
  File "upload_photos_by_exif.py", line 302, in main
    latitude, longitude, compas = get_gps_lat_long_compass(path + photo_path)
TypeError: 'NoneType' object is not iterable
```

There is EXIF written in each photo, here is gdalinfo output:

```
:~/git/uploader/upload_photos_by_exif$ gdalinfo 2016_08_01_sg2_1/2016_08_01_11_22_48_868.jpg
Driver: JPEG/JPEG JFIF
Files: 2016_08_01_sg2_1/2016_08_01_11_22_48_868.jpg
Size is 3264, 2448
Coordinate System is `'
Metadata:
  EXIF_ApertureValue=(2.81)
  EXIF_BrightnessValue=(8.31)
  EXIF_ColorSpace=1
  EXIF_DateTime=2016:08:01 11:22:48
  EXIF_DateTimeDigitized=2016:08:01 11:22:48
  EXIF_DateTimeOriginal=2016:08:01 11:22:48
  EXIF_ExifVersion=0220
  EXIF_ExposureBiasValue=(8)
  EXIF_ExposureMode=0
  EXIF_ExposureProgram=3
  EXIF_ExposureTime=(0.00215054)
  EXIF_Flash=16
  EXIF_FNumber=(2.65)
  EXIF_FocalLength=(4.03)
  EXIF_GPSImgDirection=(164.53)
  EXIF_GPSLatitude=(45) (28) (52.0536)
  EXIF_GPSLatitudeRef=N
  EXIF_GPSLongitude=(15) (33) (13.8348)
  EXIF_GPSLongitudeRef=E
  EXIF_ImageDescription={"MAPDeviceMake":"Samsung","MAPCameraMode":3,"MAPCaptureTime":"2016_08_01_11_22_48_868","MAPSettingsEmail":"hbogner+mapillary@gmail.com","MAPAPI":"LEGACY","MAPLocalTimeZone":"+0200","MAPVersionString":"2.37-jaakkoh","MAPCompassHeading":{"TrueHeading":168.06877278855276,"MagneticHeading":164.52964400818777},"MAPDeviceModel":"GT-I9100","MAPPhotoUUID":"8c153ac0-1e39-4d64-8406-9d306c1d8fbc","MAPLatitude":"45.481126","MAPAutoFocusMode":"INFINITY","MAPGPSAccuracyMeters":"3.9","MAPSequenceUUID":"e11687bf-7867-4789-98d6-823535a2ff35","MAPAltitude":"117.1","MAPSettingsUploadHash":"328a579db1b98f19de4612378fb3a4281b760bcd2e004e3802db8abbecce0523","MAPAccelerometerVector":{"z":-1.372520089149475,"y":-0.07459858059883118,"x":9.458673477172852},"MAPLongitude":"15.553843","MAPPicRotation":0}
  EXIF_ISOSpeedRatings=32
  EXIF_Make=Samsung
  EXIF_MaxApertureValue=(2.81)
  EXIF_MeteringMode=2
  EXIF_Model=GT-I9100
  EXIF_Orientation=1
  EXIF_PixelXDimension=3264
  EXIF_PixelYDimension=2448
  EXIF_SceneCaptureType=0
  EXIF_ShutterSpeedValue=(8.86)
  EXIF_Software=KTU84Q
  EXIF_UserComment=User comments
  EXIF_WhiteBalance=0
  EXIF_YCbCrPositioning=1
Image Structure Metadata:
  COMPRESSION=JPEG
  INTERLEAVE=PIXEL
  SOURCE_COLOR_SPACE=YCbCr
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 2448.0)
Upper Right ( 3264.0,    0.0)
Lower Right ( 3264.0, 2448.0)
Center      ( 1632.0, 1224.0)
Band 1 Block=3264x1 Type=Byte, ColorInterp=Red
  Overviews: 1632x1224, 816x612, 408x306
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 2 Block=3264x1 Type=Byte, ColorInterp=Green
  Overviews: 1632x1224, 816x612, 408x306
  Image Structure Metadata:
    COMPRESSION=JPEG
Band 3 Block=3264x1 Type=Byte, ColorInterp=Blue
  Overviews: 1632x1224, 816x612, 408x306
  Image Structure Metadata:
    COMPRESSION=JPEG
```
Please find a way to read those photos too.

**Comment by bogdan-telenav** [comment]
@hbogner Thanks for reporting :) can you gave me a link with some photos.

**Comment by hbogner** [comment]
Take this one:
![2016_08_01_11_22_48_868](https://cloud.githubusercontent.com/assets/794472/17745525/5ddd2d08-64ac-11e6-9f42-27679b9fbebd.jpg)

**Comment by bogdan-telenav** [comment]
Thanks

**Comment by bogdan-telenav** [comment]
@hbogner i fixed the issue. Please try again and i will appreciate any feedback

**Comment by hbogner** [comment]
Upload went OK.
Sequence shows ok on map, but when viewing sequence photos are not in order.
Take a look at the sequence:
http://openstreetview.org/map/@45.48046211462135,15.552319586277006,18z

**Comment by bogdan-telenav** [comment]
Can you send me this photos ?? i know what is the problem but i have to investigate and fix this problem in general.

**Comment by hbogner** [comment]
Here you go:
https://dl.dropboxusercontent.com/u/3220458/2016_08_01-sg2.zip

**Comment by bogdan-telenav** [comment]
Ok, i fixed this issue by sorting different the photos because there was several images with the same timestamp. 
Can you please delete from your folder where you have the images: 
-sequence_file.txt
-count_file.txt

The try again to upload those images and delete the sequence with the bug?
Thanks.
I will appreciate any feedback 👍

**Comment by hbogner** [comment]
Every photo has different time stamp.
Deleted old sequence and those files, then repeated the upload, it looks the same.

**Comment by bogdan-telenav** [comment]
If i print for several images the timestamp: 
2016_08_01-sg2_3/2016_08_01_11_22_48_868.jpg
2016-08-01 11:47:44
2016_08_01-sg2_3/2016_08_01_11_22_52_575.jpg
2016-08-01 11:47:44
2016_08_01-sg2_3/2016_08_01_11_22_53_740.jpg
2016-08-01 11:47:44
2016_08_01-sg2_3/2016_08_01_11_23_19_133.jpg
2016-08-01 11:47:44
2016_08_01-sg2_3/2016_08_01_11_23_20_369.jpg
2016-08-01 11:47:44
2016_08_01-sg2_3/2016_08_01_11_23_21_549.jpg
2016-08-01 11:47:44
2016_08_01-sg2_3/2016_08_01_11_23_22_774.jpg
2016-08-01 11:47:46

Also if i'm looking into the exif the timestamp is the same of the images...

**Comment by bogdan-telenav** [comment]
can you try again with the same steps? Thanks 👍

**Comment by hbogner** [comment]
You are looking at the wrong place for time info ;)
2016-08-01 11:47:44 is the time they were copied from phone to the computer, and they were taken hours before
 ```
gdalinfo 2016_08_01_11_22_48_868.jpg | grep Time
  EXIF_DateTime=2016:08:01 11:22:48
  EXIF_DateTimeDigitized=2016:08:01 11:22:48
  EXIF_DateTimeOriginal=2016:08:01 11:22:48
  EXIF_ExposureTime=(0.00215054)
  EXIF_ImageDescription={"MAPDeviceMake":"Samsung","MAPCameraMode":3,"MAPCaptureTime":"2016_08_01_11_22_48_868","MAPSettingsEmail":"hbogner+mapillary@gmail.com","MAPAPI":"LEGACY","MAPLocalTimeZone":"+0200","MAPVersionString":"2.37-jaakkoh","MAPCompassHeading":{"TrueHeading":168.06877278855276,"MagneticHeading":164.52964400818777},"MAPDeviceModel":"GT-I9100","MAPPhotoUUID":"8c153ac0-1e39-4d64-8406-9d306c1d8fbc","MAPLatitude":"45.481126","MAPAutoFocusMode":"INFINITY","MAPGPSAccuracyMeters":"3.9","MAPSequenceUUID":"e11687bf-7867-4789-98d6-823535a2ff35","MAPAltitude":"117.1","MAPSettingsUploadHash":"328a579db1b98f19de4612378fb3a4281b760bcd2e004e3802db8abbecce0523","MAPAccelerometerVector":{"z":-1.372520089149475,"y":-0.07459858059883118,"x":9.458673477172852},"MAPLongitude":"15.553843","MAPPicRotation":0}

```

**Comment by bogdan-telenav** [comment]
Thanks for info i will fix this tomorrow 👍

**Comment by bogdan-telenav** [comment]
Solve this issue by sorting from exif timestamp

**Comment by hbogner** [comment]
First two photos seem to be switched, I'll test on another larger sequence to see If it works fine.
http://openstreetview.org/details/14475/0

Another point: 
```
Date of recording: Aug 25, 2016
```
Shouldn't that be read from exif, and not the time of the upload?

**Comment by hbogner** [comment]
It would also be great to read mapillary sequence uuid and to automaticaly split them into different OSV sequences.
I have all my photos grouped by days, not individual sequences.

**Comment by bogdan-telenav** [comment]
We could create a script that will split the photos in several folders if the exif timestamp will differ with more than one minute. What would you say is this a good solution?

**Comment by bogdan-telenav** [comment]
@hbogner Can we still help you with sorting your photos and upload tool?

**Comment by hbogner** [comment]
@beataj-telenav Yes, that kind of a script would help. Busy currently so more feedback later.
Script could read Mapillary sequence UUID, or even timestamp as you said, and split them into several folder.

**Comment by bogdan-telenav** [comment]
@hbogner i just commit the script that separate the photos from a folder

**Comment by hbogner** [comment]
OK, give me some time to test it. Not much free time at the moment.
