### ISSUE TITLE
GPS Metadata precision

### ISSUE THREAD

**Issue by james2432** [openstreetview/uploader#8]
The data you are passing via python scripts are rounded to 4 decimal points by default
Example: 
45.48028925416667, -75.53223892111112 
becomes
45.4803,-75.5322
Which gives you a precision of about 11m at the equator (https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Geographical_coordinates#Precision)
Unless you are reusing the gps coordinates from the file to georeference where the picture is(at that point why are you passing the gps info at all?), you might want to specify the decimal precision when using the str() method
https://docs.python.org/3/library/decimal.html

**Comment by bogdan-telenav** [comment]
Thanks for reporting this issue. I didn't know that by rounding by 4 decimals will affect so much so now there is the default values from photos metadata. If you have any other suggestion let us know. Thanks again 👍
