### ISSUE TITLE
Problem with new COUNT_TO_WRITE variable

### ISSUE THREAD

**Issue by james2432** [openstreetview/uploader#9]
This issue may only occur when cancelled and then resumed. The resume may skip over some pictures in the sequence:

lets say we have 8 files
photo1 to photo8

There are 4 workers in the upload script by default, running concurrently.
So each photo that is uploaded COUNT_TO_WRITE is incremented. Now the user cancels upload because they no longer have the time or they lost internet and need to resume

lets say:
Photo1....Uploaded
Photo2....Uploaded
Photo3...Needs Upload
Photo4....Uploaded
Photo5...Needs Upload
Photo6...Needs Upload
Photo7...Needs Upload
Photo8...Needs Upload

Photo4 got uploaded because it's a smaller size or the OS decided to give it a bit more bandwith. The count in the resume file will be 3 and when it will resume, it will skip over photo3 because the file says it has already uploaded 3 files(but doesn't specify which)

**Comment by bogdan-telenav** [comment]
I will investigate this issue. Thanks  for helping 👍
